### PR TITLE
Support eslint-plugin-jest v24

### PR DESCRIPTION
**Pull request by pohnemus**
There was a breaking change that impacted our ruleset (no-test-callback: rename no-test-callback to no-done-callback) in eslint-plugin-jest v24. This makes that change as well as:
* Adds the other new "recommended" rules from v24 (why don't we just use their recommendations?)
* Sets the `peerDependencies` properly - issue from last release
* Bumps our version to v15

### CODE REVIEW

**Comment by tclindner** [comment]
> * Adds the other new "recommended" rules from v24 (why don't we just use their recommendations?)

Right now we do everything in overrides, which don't support extends. We can add the jest rules so they apply to all files. What do you think?

**Review by tclindner — APPROVED** [review]

**Comment by pohnemus** [comment]
> > * Adds the other new "recommended" rules from v24 (why don't we just use their recommendations?)
> 
> 
> 
> Right now we do everything in overrides, which don't support extends. We can add the jest rules so they apply to all files. What do you think?

Yea that's fine. Just seems like unnecessary maintenance.

**Comment by tclindner** [comment]
Sorry, not tracking your answer. Would you like to switch and have all of the jest rules apply to all files? I'm okay doing that. I would also like to get rid of the Jest global since Jest is trying to work in the direction over the next couple of major versions.

**Comment by pohnemus** [comment]
> Sorry, not tracking your answer. Would you like to switch and have all of the jest rules apply to all files? I'm okay doing that. I would also like to get rid of the Jest global since Jest is trying to work in the direction over the next couple of major versions. 

Ah sorry, I didn't follow your question :). I didn't realize this would require us to run against all files. I would like to get as close to the default / suggested approach as possible - whatever that is.

**Pull request merged**
